'use strict';
const $=id=>document.getElementById(id);
const tools={resize:['01 / PHOTO STUDIO','歡迎來到方方照相館','長圖、橫圖一起來，完整放進同一個尺寸。'],compress:['02 / PACKING SHOP','歡迎來到輕輕打包所','檔案輕一點，上架快一點。自己決定清晰度。'],poster:['03 / POSTER PRESS','歡迎來到大賣海報社','放上商品、寫好價格，讓新客人一眼看見。']};
let mode='resize',files=[],results=[],busy=false,thumbs=[];
function status(s){$('status').textContent=s}
function clearResults(){results.forEach(r=>URL.revokeObjectURL(r.url));results=[];$('result-grid').replaceChildren();$('results').hidden=true}
function selectTool(value,scroll=false){if(!tools[value])throw Error('未知工具');if(busy)throw Error('圖片處理中，請稍候');mode=value;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===mode);b.setAttribute('aria-pressed',String(b.dataset.tool===mode))});['resize','compress','poster'].forEach(v=>$(v+'-settings').hidden=v!==mode);['tool-tag','tool-title','tool-desc'].forEach((id,i)=>$(id).textContent=tools[mode][i]);clearResults();status(files.length?'圖片已就位，選好設定就可以開工。':'選好圖片，就可以開工了。');if(scroll)$('workbench').scrollIntoView({behavior:'smooth',block:'start'});return{tool:mode,selectedFiles:files.length}}
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{if(!busy)selectTool(b.dataset.tool,true)}));
function setFiles(input){if(busy)return;clearResults();thumbs.forEach(URL.revokeObjectURL);thumbs=[];let all=Array.from(input);files=all.filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=15*1024*1024).slice(0,20);$('file-list').replaceChildren();files.forEach(f=>{let im=document.createElement('img');im.src=URL.createObjectURL(f);thumbs.push(im.src);im.alt=f.name;$('file-list').append(im)});$('file-count').textContent=files.length?`已選擇 ${files.length} 張圖片`:'尚未選擇圖片';$('clear').hidden=!files.length;$('process').disabled=!files.length;status(all.length!==files.length?'部分檔案未加入：請使用 JPG、PNG、WebP，每張 15 MB 以內，最多 20 張。':files.length?'圖片已就位，選好設定就可以開工。':'選好圖片，就可以開工了。')}
$('files').addEventListener('change',e=>setFiles(e.target.files));$('clear').onclick=()=>{if(!busy){$('files').value='';setFiles([])}};
['dragenter','dragover'].forEach(ev=>$('dropzone').addEventListener(ev,e=>{e.preventDefault();$('dropzone').classList.add('dragging')}));['dragleave','drop'].forEach(ev=>$('dropzone').addEventListener(ev,e=>{e.preventDefault();$('dropzone').classList.remove('dragging')}));$('dropzone').addEventListener('drop',e=>setFiles(e.dataTransfer.files));$('quality').oninput=()=>{$('quality-label').textContent=$('quality').value+'%'};
function fit(ctx,img,x,y,w,h){const r=Math.min(w/img.width,h/img.height);ctx.drawImage(img,x+(w-img.width*r)/2,y+(h-img.height*r)/2,img.width*r,img.height*r)}
function textFit(ctx,text,x,y,maxWidth,size){ctx.font=`900 ${size}px "Microsoft JhengHei",sans-serif`;while(ctx.measureText(text).width>maxWidth&&size>20){size-=2;ctx.font=`900 ${size}px "Microsoft JhengHei",sans-serif`}ctx.fillText(text,x,y)}
async function processImages(){if(busy||!files.length)return;const job={mode,size:Number($('size').value),quality:Number($('quality').value)/100,bg:$('background').value,name:$('product-name').value.trim(),price:$('price').value,badge:$('badge').value.trim(),color:$('poster-color').value};if(mode==='poster'&&(!job.name||job.price===''||!Number.isFinite(Number(job.price))||Number(job.price)<0||Number(job.price)>9999999)){status('請填入商品名稱與 0～9,999,999 之間的售價。');return}busy=true;clearResults();$('process').disabled=true;document.querySelectorAll('input,select,[data-tool],#clear').forEach(x=>x.disabled=true);let failed=0;
try{for(let i=0;i<files.length;i++){status(`正在處理第 ${i+1} / ${files.length} 張…`);let img;try{img=await createImageBitmap(files[i]);if(img.width*img.height>40000000)throw Error('圖片尺寸過大');let c=document.createElement('canvas');c.width=job.mode==='compress'?img.width:job.mode==='resize'?job.size:1080;c.height=job.mode==='compress'?img.height:job.mode==='resize'?job.size:1350;let ctx=c.getContext('2d');ctx.fillStyle=job.mode==='resize'?job.bg:job.mode==='poster'?job.color:'#ffffff';ctx.fillRect(0,0,c.width,c.height);if(job.mode==='poster'){ctx.fillStyle='#263b43';ctx.fillRect(48,48,984,80);ctx.fillStyle='#ffffff';textFit(ctx,job.badge||'好物推薦',76,104,928,40);ctx.fillStyle='#ffffff';ctx.fillRect(48,164,984,842);fit(ctx,img,72,188,936,794);ctx.fillStyle='#263b43';textFit(ctx,job.name,54,1108,972,58);textFit(ctx,`NT$ ${Number(job.price).toLocaleString('zh-TW')}`,54,1245,972,96)}else fit(ctx,img,0,0,c.width,c.height);let blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('匯出失敗')),'image/jpeg',job.mode==='compress'?job.quality:.92));let name=files[i].name.replace(/\.[^.]+$/,'')+`-${job.mode}-${i+1}.jpg`;results.push({blob,name,url:URL.createObjectURL(blob),original:files[i].size,width:c.width,height:c.height});c.width=1;c.height=1}catch(e){failed++}finally{img?.close()}}renderResults();status(results.length?`完成 ${results.length} 張${failed?`，另有 ${failed} 張無法讀取或超過 4,000 萬像素`:''}。下載前，記得看看成品。`:'無法處理這些圖片，請改用較小且有效的圖片檔案。')}finally{busy=false;document.querySelectorAll('input,select,[data-tool],#clear').forEach(x=>x.disabled=false);$('process').disabled=!files.length}}
$('process').onclick=processImages;
function size(n){return n>=1048576?(n/1048576).toFixed(2)+' MB':(n/1024).toFixed(1)+' KB'}
function renderResults(){$('results').hidden=!results.length;results.forEach(r=>{let card=document.createElement('article');card.className='result-card';let im=document.createElement('img');im.src=r.url;im.alt=r.name;let title=document.createElement('p');title.textContent=r.name;let meta=document.createElement('small');meta.textContent=`${r.width} × ${r.height} · ${size(r.original)} → ${size(r.blob.size)}`;let a=document.createElement('a');a.href=r.url;a.download=r.name;a.textContent='下載圖片 ↓';card.append(im,title,meta,a);$('result-grid').append(card)})}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
async function zipFiles(items){let parts=[],central=[],offset=0;for(const r of items){let data=new Uint8Array(await r.blob.arrayBuffer()),name=new TextEncoder().encode(r.name),crc=crc32(data);let h=new Uint8Array(30+name.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);h.set(name,30);parts.push(h,data);let d=new Uint8Array(46+name.length),dv=new DataView(d.buffer);dv.setUint32(0,0x02014b50,true);dv.setUint16(4,20,true);dv.setUint16(6,20,true);dv.setUint16(8,0x800,true);dv.setUint32(16,crc,true);dv.setUint32(20,data.length,true);dv.setUint32(24,data.length,true);dv.setUint16(28,name.length,true);dv.setUint32(42,offset,true);d.set(name,46);central.push(d);offset+=h.length+data.length}let end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,items.length,true);ev.setUint16(10,items.length,true);ev.setUint32(12,central.reduce((n,d)=>n+d.length,0),true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
$('download-all').onclick=async()=>{const button=$('download-all');button.disabled=true;try{let blob=await zipFiles(results),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='小店長商品圖.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){status('打包失敗，請使用各張圖片下方的下載按鈕。')}finally{button.disabled=false}};
if(document.modelContext?.registerTool){const ac=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'select_image_tool',title:'選擇圖片工具',description:'切換到縮圖、壓縮或海報製作工具；不會處理或下載圖片。',inputSchema:{type:'object',properties:{tool:{type:'string',enum:['resize','compress','poster']}},required:['tool'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='tool')||!tools[input.tool])throw Error('無效的工具名稱');return selectTool(input.tool)}},{signal:ac.signal})).catch(()=>{});window.addEventListener('pagehide',()=>ac.abort(),{once:true})}catch(e){}}
